# Generated by Django 4.0.6 on 2023-05-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuneralApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Waitlist',
        ),
    ]
