# Generated by Django 4.1.6 on 2023-02-22 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FuneralApp', '0002_deceased'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, null=True)),
                ('facts', models.CharField(blank=True, choices=[('1', 'Place of birth'), ('2', 'Most recently lived in'), ('3', 'favorite hobbies'), ('4', 'favorite foods'), ('5', 'Favorite bands and musical artists'), ('6', 'Interesting facts about'), ('7', 'If you could tell anything today, what would you say?'), ('8', 'loved nothing more than'), ('9', 'Favorite place in the world'), ('10', 'Favorite sports'), ('11', 'Favorite movies'), ('12', 'profession(s)'), ('13', 'superpower'), ('14', 'proudest accomplishments'), ('15', 'pets in life'), ('17', 'Favorite ice cream flavor'), ('18', 'Places traveled to'), ('19', 'Name of High School attended'), ('20', 'Name of college attended'), ('21', 'Name of  parents'), ('22', 'Name of siblings'), ('23', 'Name of children')], max_length=100, null=True)),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FuneralApp.deceased')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
