# Generated by Django 4.1.6 on 2023-02-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuneralApp', '0003_biography'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biography',
        ),
    ]
