# Generated by Django 4.0.6 on 2023-05-17 07:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuneralApp', '0005_profile_followers_relationship_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='body_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
