# Generated by Django 4.1.6 on 2023-02-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuneralApp', '0005_biographyfacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biographyfacts',
            options={'ordering': ('id', 'deceased')},
        ),
    ]
