# Generated by Django 4.1.6 on 2023-02-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuneralApp', '0006_alter_biographyfacts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biographyfacts',
            options={'ordering': ('id',)},
        ),
    ]
