# Generated by Django 4.0.6 on 2023-06-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuneralApp', '0009_alter_tribute_options_tribute_heart_tribute_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='Awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='career',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='early_life',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='personal_life',
            field=models.TextField(blank=True, null=True),
        ),
    ]
