# Generated by Django 4.0.6 on 2023-06-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuneralApp', '0010_biography_awards_biography_career_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoalbum',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Albums/'),
        ),
    ]
