# Generated by Django 4.1.6 on 2023-02-27 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FuneralApp', '0012_alter_photoalbum_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deceased',
            name='cover_photo',
        ),
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_text', models.TextField(blank=True, null=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='CoverPhoto/')),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FuneralApp.deceased')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
