# Generated by Django 4.1.6 on 2023-03-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuneralApp', '0015_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='deceased',
            name='contributors',
            field=models.ManyToManyField(blank=True, null=True, to='FuneralApp.contributor'),
        ),
    ]
