# Generated by Django 4.1.6 on 2023-03-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuneralApp', '0016_deceased_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deceased',
            name='contributors',
        ),
    ]
