# Generated by Django 4.1.6 on 2023-03-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuneralApp', '0017_remove_deceased_contributors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
