# Generated by Django 4.1.6 on 2023-03-09 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FuneralApp', '0021_remove_contributor_memorials_contributor_memorials'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributors_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
