# Generated by Django 4.1.6 on 2023-03-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuneralApp', '0022_contributor_contributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='contributor',
            new_name='contributor_user',
        ),
    ]
