# Generated by Django 4.1.6 on 2023-03-09 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuneralApp', '0023_rename_contributor_contributor_contributor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
