# Generated by Django 4.1.6 on 2023-03-09 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuneralApp', '0024_photoalbum_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_cover', to=settings.AUTH_USER_MODEL),
        ),
    ]
